version: '3'
services:
  mongodb:
    container_name: mongodb-micro-boots
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /data/mongo:/data/mongo
    env_file:
      - env/mongo.env
    networks:
      - mongo-network
  postgressql:
    container_name: postgres-micro-boots
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - env/postgres.env
    networks:
      - postgres-network
  mysql:
    container_name: mysql-micro-boots
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - /data/mysql:/data/mysql
    env_file:
      - env/mysql.env
    networks:
      - mysql-network

networks:
  mongo-network:
  postgres-network:
  mysql-network:

